Location, 
    MillData.BZFLineNo.Value as BZFLineNo,
    MillData.TowerNo.Value as TowerNo,
    MillData.MillNo.Value as MillNo,
    MillData.MillID.Value as MillID,

    -- Motor data
    MillData.MotorDataX.Value as MotorDataX,
    MillData.MotorDataY.Value as MotorDataY, 
    MillData.MotorDataZ.Value as MotorDataZ,
    MillData.MotorDataA.Value as MotorDataA,
    MillData.ToolLife1.Value as ToolLife1,
    MillData.ToolLife2.Value as ToolLife2,
    MillData.ToolLife3.Value as ToolLife3,
    MillData.MillLifeTime.Value as MillLifeTime,
    MillData.RunTimeLastCalib.Value as RunTimeLastCalib,
    MillData.RunTimeLastGoNoGo.Value as RunTimeLastGoNoGo,
    MillData.BarcodeNo.Value as BarcodeNo,
    MillData.CaseNo.Value as CaseNo,
    MillData.WorkOffsetG54_X.Value as WorkOffsetG54_X,
    MillData.WorkOffsetG54_Y.Value as WorkOffsetG54_Y,
    MillData.WorkOffsetG54_Z.Value as WorkOffsetG54_Z,
    MillData.WorkOffsetG55_X.Value as WorkOffsetG55_X,
    MillData.WorkOffsetG55_Y.Value as WorkOffsetG55_Y,
    MillData.WorkOffsetG55_Z.Value as WorkOffsetG55_Z,
    MillData.WorkOffsetG56_X.Value as WorkOffsetG56_X,
    MillData.WorkOffsetG56_Y.Value as WorkOffsetG56_Y,
    MillData.WorkOffsetG56_Z.Value as WorkOffsetG56_Z